### ISSUE TITLE
Investigate new syntax.

### ISSUE THREAD

**Issue by proofit404** [proofit404/stories#627]
## Story definition
See final version https://github.com/proofit404/stories/issues/627#issuecomment-808525479

```python
from stories import Failure, I, Result, State, Success
```
```python
from app.repositories import create_subscription, load_category, load_profile
```
```python
class Subscribe(
    I.find_category,
    I.find_profile,
    I.check_balance,
    I.persist_subscription,
    I.show_subscription,
):

    def find_category(self, state):
        state.category = load_category(state.category_id)
        return Success()

    def find_profile(self, state):
        state.profile = load_profile(state.profile_id)
        return Success()

    def check_balance(self, state):
        if state.category.cost < state.profile.balance:
            return Success()
        else:
            return Failure()

    def persist_subscription(self, state):
        state.subscription = create_subscription(
            category=state.category, profile=state.profile
        )
        return Success()

    def show_subscription(self, state):
        return Result(state.subscription)
```
```python
subscribe = Subscribe()
```
```python
state = State(category_id=1, profile_id=1)
```
```python
result = subscribe(state)
```
```python
print(result)  # -> Subscription object
```
#### Good things:
1. State becomes a separate object (it always was that way conceptually)
2. Recursive wrap function is not necessary anymore (steps and nested stories has the same interface now)
3. User can't define multiple stories in the same class (that forces to use composition more).
4. Multiple state contracts could be attached to the same story in different use cases.
5. Stories are no longer methods but a complete class
6. We could hide story steps from result classes so there is no way to unit-test methods (force to unit-test whole stories instead)
#### Bad things
1. We need to deny subclass from stories manually
2. We need to deny mixins manually
***
## State contract 
```python
from stories import Argument, State, Variable
```
```python
class SubscribeState(State):
    category_id = Argument()
    profile_id = Argument()
    category = Variable()
    profile = Variable()
    subscription = Variable()
```
#### Good things
1. Does not couple specific entity classes (through contract definition) to the story definition. It'll become more like an interface than a direct link to the entity class.
2. State contracts could be composed using `SubscribeState & DiscountState` expression.
#### Bad things
1. It's unclear how `Expect` declaration of multiple variables should look like?
2. Rules based on nesting of state contracts will not work anymore (because state contract is flat now).
    - we can't understand if argument is required or not. See https://github.com/proofit404/stories/issues/627#issuecomment-806235589
    - #581 requires knowledge if we are in the branch of the conditional or not. See https://github.com/proofit404/stories/issues/627#issuecomment-805941999
    - #625 we will unable to understand which story declares private variable and what not. See https://github.com/proofit404/stories/issues/627#issuecomment-805952184
3. Composition `&` expression won't be that useful with `dependencies.Package`. See https://github.com/proofit404/dependencies/issues/495 https://github.com/proofit404/dependencies/issues/496 https://github.com/proofit404/dependencies/issues/497
***
## Failure protocol
```python
...
```
#### Bad things
1. I have no idea how to make failure reason works. At all. The problem lays in the level of result classes are hard coded and imported directly from `stories` library. So there are no easy way to influence them outside of story definition. I.e. we can't use the same tricks as we do with `State` object. See https://github.com/proofit404/stories/issues/627#issuecomment-803674101
***
## Usage with `dependencies`
```python
from dependencies import Injector, Package
```
```python
from rest_framework import Responce, ViewSet
```
```python
services = Package("app.services")
```
```python
class Call:

    def __init__(self, story, state_class):
        self.story = story
        self.state_class = state_class

    def __call__(self, **kwargs):
        return self.story(self.state_class(**kwargs))
```
```python
class Subscription(Injector):
    subscribe = Call
    story = services.Subscribe
    state_class = services.SubscribeState
```
```python
class Users(ViewSet):
    def create(self, request):
        result = Subscription.subscribe(**request.data)
        return Responce({"detail": "ok", "result": result})
```
#### Good things:
1. Client code (view sets) will work exactly the same way.
#### Bad things:
1. Requires 3 lines instead of one in old style.
2. Requires additional `Call` object.
***
## Conditionals
```python
from stories import I, switch, unless, when
```
```python
class Action(
    I.one,
    when("foo") > I.two,
    I.three,
):
    def one(self, state):
        ...

    def three(self, state):
        ...
```
```python
class Action(
    I.one,
    unless("foo") > I.two,
    I.three,
):
    def one(self, state):
        ...

    def three(self, state):
        ...
```
```python
from enum import Enum, auto
```
```python
class X(Enum):
    member1 = auto()
    member2 = auto()
```
```python
class Action(
    I.one,
    switch(
        "foo",
        X.member1 > I.two,
        X.member2 > I.three,
    ),
    I.four,
):
    def one(self, state):
        ...

    def four(self, state):
        ...
```
## Delegates
```python
state = State()
calculate_discount(state)
subscribe(state)
```
#### Good things:
1. Delegates implementation and concept will be way simpler in comparison to original design. 
## Cancellation
See https://github.com/proofit404/stories/issues/627#issuecomment-808814606
```python
from stories import I, cancel  # or `abort`
```
```python
class Action(
    I.one(
        ~I.cancel_one,
    ),
    I.two(
        ~I.cancel_two_a,
        ~I.cancel_two_b,
    ),
    I.three,
):
    def one(self, state):
        ...

    def two(self, state):
        ...

    def three(self, state):
        cancel()

    def cancel_two_a(self, state):
        ...

    def cancel_two_b(self, state):
        ...

    def cancel_one(self, state):
        ...
```

**Comment by proofit404** [comment]
This issue makes me think more about if we need markers at all:

* `Success` - used all the times (could be ommited)
* `Result` - return something meaningful from the story (could be replaced with `return` statement)
* `Failure+call` - short cut for `raise BusinessLogicException`
* `Failure+run` - return something error code from the story (could be replaced with `return` statement as well).
* `Next` - workaround for lack of conditionals

Maybe we could rethink our return statements from story steps.

One possible way could be tornado style `result`, `cancel` functions which works on top of internal exceptions.

**Comment by proofit404** [comment]
So to my understanding this issue would be split into at least 4 milestones:
1. New syntax using `I` base class.
2. State object instead of keyword arguments
3. Abandon execution strategies call and run.
4. Abandon `Success` and `Failure` markers.

**Comment by proofit404** [comment]
An alternative approach would be ground up rewrite of the library.

Over time `stories` grown too much technical debt.

Accompanying libraries like `dependencies` and `generics` has way higher quality control.

Half of the tickets related to missed documentation with old style functionality.

We still missing a lot of useful features.

End goal of this ticket makes half of the tickets (about 70) irrelevant.

So, we would create a new milestone and dedicate branch to it.

After we reimplement existing functionality in a new syntax we would merge milestone branch to master.

That way users will not see unfinished version of a new library in place where old semi-complete library was.

**Comment by proofit404** [comment]
See [milestone](https://github.com/proofit404/stories/milestone/15) and [branch](https://github.com/proofit404/stories/tree/milestone-15).

**Comment by proofit404** [comment]
#### Roadmap:

- [ ] Close superseded milestones
- [ ] Correct left milestones
- [ ] Close superseded issues without milestones

**Comment by proofit404** [comment]
In relation to new flat state approach:

In current version of the contract we treat `@arguments` as variables which allowed to be set anywhere. Any other variable only allowed to be set inside the story we attached contract to.

There is a consequence of such approach: different branches of same conditional statement can't declare variable with same name.

The new state approach we took - is a flat state.

In that situation we can't understand how we relate to conditionals or to the stories composition.

I want to suggest following approach to the things.

1. Any variable could be assigned by any story in the composition, not only one which define it in the contract. So we allowed to repeat variables with the same name in different state declaration.
2. We concatenate expectations from variable validators. All of them still needs to normalize value to the same type and value.
3. The only thing that`Argument` change in comparison to `Variable` - allow to pass variables to the `State(...)` constructor. Variables could only be assigned to state. Arguments could be both passed and assigned.
4. Singular `Expect` would be replaced with `Variable`.

Consequences of new appoach: branches in conditionals does not need additional semantic to check variables.

**Comment by proofit404** [comment]
In relation to private variables:

Different stories would like to have different private variables.

A variable with the same name defined in different stories could have different validators attached to them which will normalize to different values.

This semantic requires understanding in what story what variable was defined.

A new flat state approach would be unable to determine these structure.

As we suggested in the #474 - the best practice to follow is immediate encapsulation of responses from different services in the some domain object.

That makes private variables in stories less valuable than I initially thought.

I would like to remove private variables proposal and suggest to users not to store garbage in the state of domain process.

**Comment by proofit404** [comment]
In relation to passed story arguments verification:

Lets imagine we have this picture:

```python
story = C1(
    B1(
        A1(),
        A2(),
    ),
    B2(
        A3(),
        A4(),
    ),
)

state_class = (
    C1State & B1State & A1State & A2State & B2State & A3State & A4State
)

state = state_class() # error
```
In that case, we will not be able to determine difference between `c1v1` (required in the state constructor) and `a1v1` (could be set by steps).

In reality, if we have tests the very first one would show us we missed parameters.

But still it's PITA to work with.

**Comment by proofit404** [comment]
## Updated version

```python
from stories import I, State, Story

from app.repositories import create_subscription, load_category, load_profile


class Subscribe(Story):
    I.find_category
    I.find_profile
    I.check_balance
    I.persist_subscription

    def find_category(self, state):
        state.category = self.load_category(state.category_id)

    def find_profile(self, state):
        state.profile = self.load_profile(state.profile_id)

    def check_balance(self, state):
        if state.category.cost > state.profile.balance:
            raise Exception

    def persist_subscription(self, state):
        state.subscription = self.create_subscription(
            category=state.category, profile=state.profile
        )


subscribe = Subscribe(
    load_category=load_category,
    load_profile=load_profile,
    create_subscription=create_subscription,
)

state = State(category_id=1, profile_id=1)

subscribe(state)

print(state)
```
## PoC 
```python
class Step:
    def __init__(self):
        self.collected = []
    def __getattr__(self, name):
        self.collected.append(name)


class StoryType(type):
    def __prepare__(name, bases):
        return {'I': Step()}
    def __new__(cls, name, bases, namespace):
        print(namespace['I'].collected)
        del namespace['I']
        return type.__new__(cls, name, bases, namespace)


class Story(metaclass=StoryType):
    pass


I = None # make flake8
```

**Comment by proofit404** [comment]
This issue will be kept until we create pull request from the `milestone` branch to the `master`.

**Comment by proofit404** [comment]
Contrib package extraction would be a side effect of work no this feature.

**Comment by proofit404** [comment]
## Cancellation

I came to the conclusion - it should not be implemented in the first place.

It's concept is based around cancellation of steps.

But we should focus on domain processes.

In that case conditionals and separate story should be closer to expert thinking.

**Comment by proofit404** [comment]
Our new `release` & `develop` branch approach does not require dedicated issue to merge `develop` into `release`.

This issue contains a log of 3 weeks of thinking on the problem.

Final result was decomposed into milestone tickets.

So, this issue could be closed safely.

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
franee, @Thavatchai-lab, @0xwilliampeter, @D3athGr1p, @vthinkxie, @raydzast, @yorennz, @Huge, @GuilhermeC18, @tony92151, @yuanjunliang, @bwash105, @ZiJiaW, @lucoo01, @vikusik-simpapusik, @claudiopb, @lutz, @ehelvacikoylu, @ikozigbo, @yrzx404, @HelloMokuzai, @cybernetics, @chauhansagun, @OftenUser, @muflihunaf, @hambalee, @westerncj, @Meharab, @0xCFx, @MrPops, @Mi-kio, @mengguang, @darshakthakore, @gaurav1911, @SiddharthaMadhav, @vinmay, @jerrywjh, @SharmaRajan, @DylanHe, @simon-xia, @Duy-Thanh, @valkx, @defconst, @Grrr1Want2, @juhi24, @chuyenbka, @fcjz, @pc163, @najahlino, @stenppfnDevious3901, @zzf03680147, @sjin09, @willshome, @halleluyhwhyeshua, @roshanmirajkar, @otaha178, @drpaulow, @RaoPrashanth, @ngoct47449, @ANTCPU, @mahfuzali, @nlipartiia-hacken, @yizhzhang, @yabeen, @baldychristophe, @maddox-j, @12knnights, @csawe, @asreejith-vcrs, @deniskv, @jebron, @gc87, @autoshgame, @rahife, @gsxgoldenlegendary, @sun-driedtomatoes, @lvm, @amazingchow, @anneouyang, @DawnLIU35, @hanke-janson, @ichyycc, @idolpx, @paritosh9199, @gbrugger, @bod17, @NicolasVidalDuque, @ImShalev, @rahuldadz, @CONVORDIV, @PresidentNick, @zhuzhuxia480, @Dec1n, @mmilewczyk, @lladawn, @Sitaras, @Keeplee33, @Kaleb47, @ugeblainebradypp, @krittakondev, @vFrankPZhang, @JustCallMe-AK, @bundubuduri, @AntonioRas, @theedtron, @yjw258, @cs-w0r1d, @joshua2049, @Payne0, @holden-nelson, @jimmy8me7, @oldmonad, @softish, @ivancevich, @AndresNaza, @chuck940, @Jae-eun, @96piku, @tomschr, @HugoDoyon, @Aaron0Dawn, @jarbus, @tonydero, @alfonso21M, @Filipsys, @maxifom, @0xcoder101, @whysokara, @jgh2i, @hanguyen-asana, @azureyang, @0xkzam, @ihrifat2, @nafi-ansary, @jvhvvvn, @cicimen, @cligrenet, @izabelakowal, @zhujun98, @radhikax, @nassersala, @Derek-X-Wang, @TheBatmanIRL, @SoumojitNag, @tarvos21, @abidpu19, @devmarkpro, @likeaixiDanissss, @SAKANA7, @dahan6669, @work-jlsun, @git618, @aekanshd, @liuyuhua1984, @AayushXtreme, @cmacinnes, @oiwn, @rotorhead412, @kiat, @MalloryLeeWong, @lucianarferreira, @kinght200, @cygnus-xr1, @khinshankhan, @xuethousand, @oantoro, @akshymalvia, @gulahmed, @Ghoststep, @zweily, @vinipl87, @crackprivatekeys, @beskay, @oaizab, @Jxust-ZL, @arejula27, @jesen-surjadi, @seungjulee, @RealBeepMcJeep, @aichinobi, @PeterMyrobot, @viktaur, @phannhu92, @rassveett, @maiflys, @kithmal, @SteveYuOWO, @Shah0912, @dideler, @gsyx666, @1111Sirius1111, @GitP2826, @appsarak, @Hann, @MartinrVal, @ferdianarid, @dingshanliang
